### ISSUE TITLE
composer dependencies problem?

### ISSUE THREAD

**Issue by ghost** [coduo/phpspec-matcher-extension#1] opened 2014-06-14 14:25 UTC
require-dev:

``` json
"coduo/phpspec-matcher-extension": "dev-master",
"coduo/php-to-string": "1.0.*@dev"
```

minimum-stability: dev.

`php composer.phar update` output:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - coduo/php-matcher v1.0.0 requires coduo/php-to-string 0.1.* -> no matching package found.
    - coduo/php-matcher 1.0.2 requires coduo/php-to-string 0.1.* -> no matching package found.
    - coduo/php-matcher 1.0.1 requires coduo/php-to-string 0.1.* -> no matching package found.
    - coduo/php-matcher 1.0.2 requires coduo/php-to-string 0.1.* -> no matching package found.
    - coduo/phpspec-matcher-extension dev-master requires coduo/php-matcher 1.0.*@dev -> satisfiable by coduo/php-matcher[1.0.2, 1.0.1, v1.0.0].
    - Installation request for coduo/phpspec-matcher-extension dev-master -> satisfiable by coduo/phpspec-matcher-extension[dev-master].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by cordoval** [comment] 2014-09-11 21:02
the problem is php-matcher i am creating the issue there now

**Comment by cordoval** [comment] 2014-09-11 21:14
solved it with this

```
        "coduo/phpspec-prepare-extension": "~1.0@dev",
        "coduo/phpspec-data-provider-extension": "~1.0@dev",
        "coduo/phpspec-matcher-extension": "dev-patch-1@dev"
...

"repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:cordoval/phpspec-matcher-extension"
        }
    ]
```

**Comment by cordoval** [comment] 2014-09-15 22:12
bump @norzechowicz close it please

**Closed as completed** 2014-09-16 06:34 UTC
